### PR TITLE
Specify Ruby version

### PR DESCRIPTION
**Pull request by weakish**
to 3.1.4 in .ruby-version file,
since jekyll of this project does not work with Ruby 3.2.

Note:

Ruby 3.2 removes a bunch of methods from the top level Object class.
This will trigger a Liquid Exception: undefined method `tainted?`
for the jekyll version used by this project.

### CODE REVIEW

**Comment by weakish** [comment]
For reference, this the error I encountered when I run `bundle exec jekyll serve` on Ruby 3.2.2

```
  Liquid Exception: undefined method `tainted?' for "16 Jan 2022":String in /workspaces/simple.css-site/_layouts/post.html
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/local/rvm/gems/ruby-3.2.2/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in `taint_check': undefined method `tainted?' for "16 Jan 2022":String (NoMethodError)
```

And here is [a link to a related discussion on Jekyll forum][jekyll].

[jekyll]: https://talk.jekyllrb.com/t/liquid-4-0-3-tainted/7946

**Comment by kevquirk** [comment]
I'm not sure this is an appropriate change to make. For example, I have an M1 Mac running 3.0.0 and upgrading is a PITA. This would be a breaking change for me, and as the only maintainer, I think that's very important.

I think a better solution is if people want to copy the site, fork and implement this change themselves.

**Comment by weakish** [comment]
> For example, I have an M1 Mac running 3.0.0

Then what about specifying `3.0.0` in `.ruby-version` instead?
(Previously I chose `3.1.4` just because it is the most recent compatible release.)

> This would be a breaking change

`.ruby-version` will not affect the system ruby version on local machine.
`.ruby-version` is a hint to inform potential contributors which Ruby version should be used,
and in certain environments, it will result in ruby version switch automatically:

- On dev/local machine, if rbenv or rvm (popular options for managing multiple Ruby versions) is installed, then it will automatically change to the Ruby version specified in `.ruby-version`. If no such tools installed, then `.ruby-version` has no effect at all and Jekyll will continue to use system ruby version.
- Since `.ruby-version` is a popular practice among Ruby projects, a lot of cloud service providers also support it, for example [Netlify], GitHub Codespaces and [GitHub Actions][gh].

[Netlify]: https://docs.netlify.com/configure-builds/manage-dependencies/#ruby
[gh]: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby

**Comment by kevquirk** [comment]
It's only me and @lkhrs who maintain the site, this has never been an issue, so why would we need to specify a Ruby version? It works for us, and if others want to fork it and specify the version, they can.

I suppose what I'm trying to say is I don't understand the value this adds to the project? Maybe I'm missing something? Apologies if I am.

**Comment by kevquirk** [comment]
Re-opening as I think there's more conversation to be had here.

**Comment by weakish** [comment]
It makes the developer experience of potential contributors a bit easier if their default ruby version is 3.2, and they have a ruby version manager (which supports `.ruby-version`) installed. Otherwise, they need to either manually switch to a Ruby version (<3.2) or run `bundle update` to update jekyll & liquid to a more recent version.

However, I do agree that since "this has never been an issue" for current maintainers, `.ruby-version` is not necessary and introducing it will add a bit of overhead (the version need to be updated).

**Comment by waldyrious** [comment]
> the version need to be updated

But if that file is not picked up unless one uses a Ruby version manager, it seems like its presence would not affect current maintainers anyway (but please correct me if I'm wrong); and it not being updated would only affect contributors like you — in which case a PR updating that version would be appropriate to make things easier for the next guy, as you're doing here. :heart:

In any case, I would definitely support making the development setup by people other than the current maintainers easier, because people's availability come and go and it would be a pity to risk this project becoming unmaintained down the road — a risk that increases if we don't actively minimize friction points like the one you bumped into [as described above](https://github.com/kevquirk/simple.css-site/pull/23#issuecomment-1711074726). Making the Ruby version explicit is one of the aspects that improves this DX for new contributors, and assuming it doesn't affect current maintainers, I'd suggest it would be a net positive.

**Comment by kevquirk** [comment]
Thanks for the conversation, folks. The additional context helps. I've just added a `.ruby-version` and pushed it. I've set it to `3.0.0`.
